apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: externaldns
    kubebuilder.k8s.io: 1.0.0
  name: dnsendpoints.externaldns.k8s.io
spec:
  group: externaldns.k8s.io
  names:
    kind: DNSEndpoint
    plural: dnsendpoints
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              endpoints:
                items:
                  properties:
                    dnsName:
                      type: string
                    labels:
                      type: object
                    providerSpecific:
                      items:
                        properties:
                          name: 
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    recordTTL:
                      format: int64
                      type: integer
                    recordType:
                      type: string
                    targets:
                      items:
                        type: string
                      type: array
                  type: object
                type: array
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object